### ISSUE TITLE
Method arguments in geom_quasirandom doesn't seem to work

### ISSUE THREAD

**Issue by thomasdebeus** [eclarke/ggbeeswarm#36]
I'm trying to create a `ggbeeswarm` plot but I can't seem to get the `method` argument working within the geom_quasirandom function. Thanks in advance!

```
    join_anp_vgn %>%
      ggplot(aes(x = groei_daling_zetels, 
                 y = lokaal_gegroepeerd,
                 color = groei_daling_zetels)) +
      geom_quasirandom(groupOnX = F,
                       method = "smiley") +
      scale_x_continuous(breaks = seq(-4,6,1),
                         limits = c(-4,6)) +
      scale_color_gradient2(low = "#B10026", 
                            mid = "#FFFFBF", 
                            high = "#4575B4", 
                            midpoint = 0) +
      theme_minimal() +
      theme(legend.position = 0,
            panel.grid.minor.x = element_blank()) +
      labs(x = "",
           y = "")
```

![](https://i.imgur.com/n1LYABJ.png)

**Comment by eclarke** [comment]
Hi @thomasdebeus, when I try to replicate this using the iris dataset, I am able to use `method="smiley"` okay:
```r
ggplot(iris, aes(x=Sepal.Length, y=Species)) + 
    geom_quasirandom(method="smiley", groupOnX = F)
```

![image](https://user-images.githubusercontent.com/372767/39884761-e42e9eb2-5458-11e8-9e5d-5455afe92e0c.png)

However, I see that if round the x-axis values so that they're integers, it looks like yours: 
```r
ggplot(iris, aes(x=round(Sepal.Length), y=Species)) + 
    geom_quasirandom(method="smiley", groupOnX = F) 
```

![image](https://user-images.githubusercontent.com/372767/39884879-2effaf26-5459-11e8-9d99-69e5d8e87430.png)

quasirandom/beeswarm won't jitter along the continuous axis because it would change the representation of the data. Are your x-axis data exactly integer values?

**Comment by thomasdebeus** [comment]
Yes, they’re on c(-4, -3, -2, -1, 0, 1, 2, 3, 4, 5) 

So that won’t work? To get ggbeeswarm to work at least one variable has to be a double? I see what you mean that it otherwise distords the visual representation.

**Comment by eclarke** [comment]
It's not that one variable has to be a double, it's that ggbeeswarm will only move the points along the categorical axis, in your case the y-axis. The position of points along the continuous axis is kept constant because those are the values from the data. If you want to add fake jitter to your points, you can do that randomly with the built-in `jitter` function- it'd be something like this: 
```r
ggplot(iris, aes(x=jitter(Sepal.Length), y=Species)) + 
    geom_quasirandom(method="smiley", groupOnX = F) 
```
And in that case it would disperse along the x-axis as you want. Though again, this does give the impression that there's more variance in your data than there actually is.
