### ISSUE TITLE
position_beeswarm gone?

### ISSUE THREAD

**Issue by Ari04T** [eclarke/ggbeeswarm#45]
Is position_beeswarm gone in the latest experimental version (as Sept 8/2019)? 
If so, is there a new function that we should use to replace position_beeswarm?

Thanks!

**Comment by sherrillmix** [comment]
Was position_beeswarm working in the non-github version on CRAN? Last I check ggplot had removed it out from under us. For example, with v0.6 off CRAN:

```
ggplot2::qplot(class, hwy, data = ggplot2::mpg, position=position_beeswarm())
Warning message:
`position` is deprecated
```

![position](https://user-images.githubusercontent.com/1217152/64527676-8ce18380-d2d4-11e9-9001-90dec3ea2a86.png)


If I understand things correctly, "deprecated" is a mild understatement since it simply ignore the `position` argument.

The alternative would be to use the geom_beeswarm:

```
ggplot2::qplot(class, hwy, data = ggplot2::mpg)+geom_beeswarm()
```

![bee](https://user-images.githubusercontent.com/1217152/64527797-e0ec6800-d2d4-11e9-8774-c670b880b107.png)

**Comment by vacon04** [comment]
Yes, position_beeswarm was working correctly, although not to generate the actual beeswarm, but the position for labels in a different geom layer.

`ggplot(mtcars, aes(factor(cyl), mpg)) +
    geom_beeswarm(cex = 3) +
    geom_text(aes(label = hp),
              position = position_beeswarm(cex = 3))`

![Rplot](https://user-images.githubusercontent.com/7259598/64530842-12b4fd00-d2dc-11e9-8983-95b503dee6e2.png)

**Comment by sherrillmix** [comment]
Thanks. It's good to have a MWE since I don't really use that functionality. 

I'll have to think about that since getting beeswarm to work properly with ggplot requires hooking into `makeContent` which I don't think will play nicely with `position`.  So we're at an edge case of ggplot that is simple in base graphics and seems to be a bit of pain here.

**Comment by eclarke** [comment]
Should be fixed in latest version
