### ISSUE TITLE
position_beeswarm gives incorrect positions

### ISSUE THREAD

**Issue by dperlman** [eclarke/ggbeeswarm#8]
Beeswarm position doesn't seem to work right at the moment.
(position_quasirandom works fine.)
I looked through the code history briefly but I wasn't able to find anything clearly related to this problem, sorry!

qplot(Species, Sepal.Length, data=iris, position=position_beeswarm())
![ggbeeswarm_failure](https://cloud.githubusercontent.com/assets/8398233/11970356/07ad3ef6-a8ef-11e5-8d99-69b1664ba2c0.png)

RStudio Version 0.99.489
beeswarm v.0.2.1
vipor v.0.3.2
I downloaded the latest commit on master:
Latest commit 2c36625  on Nov 12 @eclarke eclarke Merge pull request #7 from smsaladi/master 
(The latest actual release from Oct. 22 doesn't work either because the library name for vipor is still at violinpoint.)

**Comment by eclarke** [comment]
thanks for the heads up. out of curiosity, what version of ggplot2 are you using?

**Comment by dperlman** [comment]
ooooh good point. Mine was at 1.0.1. I just updated to the current ggplot2 2.0.0.
But... now it looks even worse.
```
> qplot(Species, Sepal.Length, data=iris, position=position_beeswarm())
Warning message:
`position` is deprecated 
```
![ggbeeswarm_failure2](https://cloud.githubusercontent.com/assets/8398233/11970527/70333072-a8f2-11e5-8f40-71d4e8187ed0.png)

**Comment by eclarke** [comment]
Oh whoops- I was about to say that I haven't fixed it to work with ggplot2 2.0.0 yet, but it looks like it's a problem with both. Thanks for letting us know, we'll try to get a fix shortly!

**Comment by sherrillmix** [comment]
ggplot2 "deprecated" (actually completed deleted) positions so we had to change over to geoms. I think the code should work now as:
`qplot(Species, Sepal.Length, data=iris)+geom_beeswarm(cex=3)`
I need to see if ggplot2 2.0 gives access to plotting information so that beeswarm can automatically fit the points. In the meantime, I guess it's hand twiddling `cex=` or using `geom_quasirandom`.
![test](https://cloud.githubusercontent.com/assets/1217152/11996669/04fb9fe8-aa36-11e5-95b8-1f934dc16a02.png)

**Comment by sherrillmix** [comment]
I'm going to close the issue but let us know if it is in fact still a problem.
