### ISSUE TITLE
Arguments not explained in documentation

### ISSUE THREAD

**Issue by MarekGierlinski** [eclarke/ggbeeswarm#91]
Documentation for `geom_beeswarm` contains the following:

```
method      Method for arranging points (see Details below)
priority    Method used to perform point layout (see Details below)
```

However, there are no details below and the arguments are not explained, in particular there are no possible values given.

**Comment by mvanaman** [comment]
Sorry to revive closed issue and I know this is not a huge deal – but would it be possible at some point to copy argument details for `method`, `priority`, and `corral` so that they show up in the help window in RStudio (i.e., for `?geom_beeswarm()`), possibly along with the relevant examples from the README page?
